services:
  - type: web
    name: instagram-webhook
    runtime: python
    buildCommand: "apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    envVars:
      - key: INSTAGRAM_USER_ID
        sync: false
      - key: INSTAGRAM_ACCESS_TOKEN
        sync: false
      - key: YT_CLIENT_ID
        sync: false
      - key: YT_CLIENT_SECRET
        sync: false
      - key: YT_REFRESH_TOKEN
        sync: false
